### ISSUE TITLE
Use supported NGINX image

### ISSUE THREAD

**Issue by rlaurika** [CSCfi/spark-openshift#14]
The rlaurika/openshift-nginx image is not supported or kept up to date, so it would be better to use some different image instead. Old unsupported images may have security vulnerabilities in them and eventually the software versions in them become deprecated.

One option for a replacement would be the Bitnami NGINX image that can be found here: https://hub.docker.com/r/bitnami/nginx

It uses a non-root user and does not try to bind port 80. Based on a quick test it seems to launch in OpenShift and serves content.

**Comment by juhahu** [comment]
We'll check that Bitnami NGINX and go for replacing current image.

**Comment by juhahu** [comment]
Replaced rlaurika/openshift-nginx with modified bitnami nginx. Changes applied to dev-nginx branch.
